### ISSUE TITLE
PICARD client launch issue

### ISSUE THREAD

**Issue by Rautmare-Sneha** [ElementAI/picard#133]
Hi

I am executing the Eval code on the spider data with picard using docker image

provided 777 permission to mentioned 2 directories
'make eval'
inside docker -> Install stanza package
python3 seq2seq/eval_run_seq2seq.py configs/spider/eval_spider_rasat_4160.json
After preprocessing , generating relation i got following error :

`
Use relation model.
Traceback (most recent call last):
File "seq2seq/eval_run_seq2seq.py", line 309, in
main()
File "seq2seq/eval_run_seq2seq.py", line 197, in main
model = model_cls_wrapper(T5ForConditionalGeneration).from_pretrained(
File "seq2seq/eval_run_seq2seq.py", line 184, in
model_cls=model_cls, picard_args=picard_args, tokenizer=tokenizer, schemas=dataset_splits.schemas
File "/app/seq2seq/utils/custom_picard_model_wrapper.py", line 482, in with_picard
asyncio.run(_init_picard(), debug=False)
File "/opt/conda/lib/python3.7/asyncio/runners.py", line 43, in run
return loop.run_until_complete(main)
File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
return future.result()
File "/app/seq2seq/utils/custom_picard_model_wrapper.py", line 126, in _init_picard
await _register_schema(db_id=db_id, db_info=db_info, picard_client=client)
File "/app/seq2seq/utils/custom_picard_model_wrapper.py", line 132, in _register_schema
await picard_client.registerSQLSchema(db_id, sql_schema)
thrift.py3.exceptions.TransportError: (<TransportErrorType.UNKNOWN: 0>, 'Channel is !good()', 0, <TransportOptions.0: 0>)

`

Enviornment : Macbook

**Comment by lucky-jack-dev** [comment]
Hello, I fixed this problem by changing time.sleep(1) to 10 in line seq2seq/utils/picard_model_wrapper.py 95. I guess because the child process has not started successfully, the main process connected, so this error will be reported.

**Comment by Rautmare-Sneha** [comment]
Thank you @Tomcatiiii for the suggestion. I updated code as per your comment, but still facing same error. Is there any other way to resolve it. I am trying to reproduce the results of RASAT+PICARD, and facing this issue.

**Comment by Jessie-gjx** [comment]
hi, could you fix it? I was also stuck on that point after I change the time.sleep
