### ISSUE TITLE
make build-eval-image failing

### ISSUE THREAD

**Issue by smittal10** [ElementAI/picard#22]
Hi, 

We are trying to run the docker image for evaluation of the PICARD model. On executing "make build-eval-image", it throws an error "ERROR exporting to image, error: failed to solve: server message: insufficient_scope: authorization failed" after build completes successfully.

Without building the image, "make eval" shows "picard not available". 

Can someone point out what we are doing wrong here? We want to evaluate the T5 model with PICARD on spider!

Thanks.

**Comment by tscholak** [comment]
Hi @smittal10!

Thanks for trying out PICARD!
The error you saw during `make build-eval-image` is expected. If you look at the definition of that target in the `Makefile`, you can see that this command will try to push the new image to my personal docker hub account. However, I am the only one who can write there. If you need to rebuild the image, please use your own docker repository instead or, even better, open a PR and push your changes to this GitHub repository so that everyone can benefit from your changes!

Meanwhile, I'm looking into your "picard not available" error. That should not happen.

Best,
Torsten

**Comment by tscholak** [comment]
Update: I could not reproduce the "picard not available" error. This is what I see:
```
make eval                                                                                                                       !10035
docker pull tscholak/text-to-sql-eval:e7dc6eef9d9eb68da58ee32010e423ec37fe1da5
e7dc6eef9d9eb68da58ee32010e423ec37fe1da5: Pulling from tscholak/text-to-sql-eval
...
Digest: sha256:5ea709a764d3019cc8351f1c6f7bb3dc77e6d2c038a753ed47b7ec8dac974b62
Status: Downloaded newer image for tscholak/text-to-sql-eval:e7dc6eef9d9eb68da58ee32010e423ec37fe1da5
docker.io/tscholak/text-to-sql-eval:e7dc6eef9d9eb68da58ee32010e423ec37fe1da5
mkdir -p -m 777 eval
mkdir -p -m 777 transformers_cache
mkdir -p -m 777 wandb
docker run \
		-it \
		--rm \
		--user 13011:13011 \
		--mount type=bind,source=/Users/torsten.scholak/Projects/ServiceNow/picard/eval,target=/eval \
		--mount type=bind,source=/Users/torsten.scholak/Projects/ServiceNow/picard/transformers_cache,target=/transformers_cache \
		--mount type=bind,source=/Users/torsten.scholak/Projects/ServiceNow/picard/configs,target=/app/configs \
		--mount type=bind,source=/Users/torsten.scholak/Projects/ServiceNow/picard/wandb,target=/app/wandb \
		tscholak/text-to-sql-eval:e7dc6eef9d9eb68da58ee32010e423ec37fe1da5 \
		/bin/bash -c "python seq2seq/run_seq2seq.py configs/eval.json"
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'

CondaEnvException: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.

wandb: W&B syncing is set to `offline` in this directory.  Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Downloading and preparing dataset spider/spider to /transformers_cache/spider/spider/1.0.0/3c571ccbabdc104a8d1f14edff4ce10d09d7724b0c3665fc42bec1ed51c84bf3...
Dataset spider downloaded and prepared to /transformers_cache/spider/spider/1.0.0/3c571ccbabdc104a8d1f14edff4ce10d09d7724b0c3665fc42bec1ed51c84bf3. Subsequent calls will reuse this data.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 66.66it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 1034/1034 [01:07<00:00, 15.21ex/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  3.87ba/s]
***** Running Evaluation *****
  Num examples = 1034
  Batch size = 1
  1%|█▏                                                                                                | 12/1034 [05:55<8:14:43, 29.04s/it]
```

**Comment by tscholak** [comment]
@smittal10 any luck?

**Comment by Young1993** [comment]
Hi, when I run the ` make eval`, errors happen: 

docker pull tscholak/text-to-sql-eval:e37020b6eee18bff865d9d2ba852bd636f3ed777
e37020b6eee18bff865d9d2ba852bd636f3ed777: Pulling from tscholak/text-to-sql-eval
Digest: sha256:e4710b52c1c74397d87f3d8065630e7527c47014dbf8521ecc78bbc54a5f4cdd
Status: Image is up to date for tscholak/text-to-sql-eval:e37020b6eee18bff865d9d2ba852bd636f3ed777
docker.io/tscholak/text-to-sql-eval:e37020b6eee18bff865d9d2ba852bd636f3ed777
mkdir -p -m 777 eval
mkdir -p -m 777 transformers_cache
mkdir -p -m 777 wandb
docker run \
	-it \
	--rm \
	--user 13011:13011 \
	--mount type=bind,source=/home/wh/picard/eval,target=/eval \
	--mount type=bind,source=/home/wh/picard/transformers_cache,target=/transformers_cache \
	--mount type=bind,source=/home/wh/picard/configs,target=/app/configs \
	--mount type=bind,source=/home/wh/picard/wandb,target=/app/wandb \
	tscholak/text-to-sql-eval:e37020b6eee18bff865d9d2ba852bd636f3ed777 \
	/bin/bash -c "python seq2seq/run_seq2seq.py configs/eval.json"
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'

CondaEnvException: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.

wandb: W&B syncing is set to `offline` in this directory.  Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Downloading and preparing dataset spider/spider to /transformers_cache/spider/spider/1.0.0/3c571ccbabdc104a8d1f14edff4ce10d09d7724b0c3665fc42bec1ed51c84bf3...
Traceback (most recent call last):
  File "seq2seq/run_seq2seq.py", line 270, in <module>
    main()
  File "seq2seq/run_seq2seq.py", line 148, in main
    tokenizer=tokenizer,
  File "/app/seq2seq/utils/dataset_loader.py", line 89, in load_dataset
    dataset_dict=_spider_dataset_dict(),
  File "/app/seq2seq/utils/dataset_loader.py", line 45, in <lambda>
    path=data_args.dataset_paths["spider"], cache_dir=model_args.cache_dir
  File "/opt/conda/lib/python3.7/site-packages/datasets/load.py", line 1117, in load_dataset
    use_auth_token=use_auth_token,
  File "/opt/conda/lib/python3.7/site-packages/datasets/builder.py", line 637, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "/opt/conda/lib/python3.7/site-packages/datasets/builder.py", line 704, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/transformers_cache/modules/datasets_modules/datasets/spider/3c571ccbabdc104a8d1f14edff4ce10d09d7724b0c3665fc42bec1ed51c84bf3/spider.py", line 97, in _split_generators
    downloaded_filepath = dl_manager.download_and_extract(_URL)
  File "/opt/conda/lib/python3.7/site-packages/datasets/utils/download_manager.py", line 284, in download_and_extract
    return self.extract(self.download(url_or_urls))
  File "/opt/conda/lib/python3.7/site-packages/datasets/utils/download_manager.py", line 197, in download
    download_func, url_or_urls, map_tuple=True, num_proc=download_config.num_proc, disable_tqdm=False
  File "/opt/conda/lib/python3.7/site-packages/datasets/utils/py_utils.py", line 197, in map_nested
    return function(data_struct)
  File "/opt/conda/lib/python3.7/site-packages/datasets/utils/download_manager.py", line 217, in _download
    return cached_path(url_or_filename, download_config=download_config)
  File "/opt/conda/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 299, in cached_path
    use_auth_token=download_config.use_auth_token,
  File "/opt/conda/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 606, in get_from_cache
    raise ConnectionError("Couldn't reach {}".format(url))
ConnectionError: Couldn't reach https://drive.google.com/uc?export=download&id=1_AckYkinAnhqmRQtGsQgUKAnTHxxX5J0

wandb: Waiting for W&B process to finish, PID 33... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /app/wandb/offline-run-20211130_040709-2ifmtjxy
wandb: Find logs at: ./wandb/offline-run-20211130_040709-2ifmtjxy/logs/debug.log
wandb: 
Makefile:139: recipe for target 'eval' failed
make: *** [eval] Error 1

**Comment by tscholak** [comment]
Hi @Young1993, I'm afraid this doesn't seem to be a problem specific to this project, and I would advise you to seek help elsewhere.

The underlying problem seems to be that access to Google drive has been limited from your location and/or your data centre. Unfortunately, this is where the Spider dataset is officially downloaded from.

**Comment by Saghar-Hosseini** [comment]
Hi @tscholak 
I have Sudo access on my GPU machine and was able to run "make train" successfully, however "make eval" throws this error:

Traceback (most recent call last):
  File "seq2seq/run_seq2seq.py", line 276, in <module>
    main()
  File "seq2seq/run_seq2seq.py", line 51, in main
    picard_args, model_args, data_args, data_training_args, training_args = parser.parse_json_file(
  File "/app/seq2seq/utils/dataset_loader.py", line 87, in load_dataset
    metric = _spider_metric()
  File "/app/seq2seq/utils/dataset_loader.py", line 48, in <lambda>
    path=data_args.metric_paths["spider"], config_name=data_args.metric_config, test_suite_db_dir=data_args.test_suite_db_dir
  File "/opt/conda/lib/python3.7/site-packages/datasets/load.py", line 819, in load_metric
    dataset=False,
  File "/opt/conda/lib/python3.7/site-packages/datasets/load.py", line 446, in prepare_module
    dynamic_modules_path = dynamic_modules_path if dynamic_modules_path else init_dynamic_modules()
  File "/opt/conda/lib/python3.7/site-packages/datasets/load.py", line 82, in init_dynamic_modules
    hf_modules_cache = init_hf_modules(hf_modules_cache)
  File "/opt/conda/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 56, in init_hf_modules
    os.makedirs(hf_modules_cache, exist_ok=True)
  File "/opt/conda/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'transformers_cache/modules'

TIA for your help!

**Comment by tscholak** [comment]
Closing due to inactivity.
