### ISSUE TITLE
Error: Internal server error 500 while running make serve. 

### ISSUE THREAD

**Issue by ishmeetk** [ElementAI/picard#49]
Hello @tscholak and the team. I am trying to use make serve for the T5+PICARD and run into error 500 on the fastapi page. Below is crash trace and also my configs. Thank you in advance.
<img width="783" alt="Screen Shot 2022-01-26 at 1 55 32 PM" src="https://user-images.githubusercontent.com/22566345/151253658-2ba0f92c-749b-4f2e-b08a-c096121948ce.png">
<img width="1708" alt="Screen Shot 2022-01-26 at 1 50 52 PM" src="https://user-images.githubusercontent.com/22566345/151253680-078a9028-d985-4c14-b8d4-fd6f0f9b83b3.png">
<img width="1843" alt="Screen Shot 2022-01-26 at 1 50 59 PM" src="https://user-images.githubusercontent.com/22566345/151253710-5e1d59a4-b3f4-48b7-985c-c7ceb5764d2f.png">

NFO:     172.17.0.1:62060 - "GET /ask/transactions/what%20is%20category%20for%20Canada%3F HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/conda/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.7/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/conda/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/opt/conda/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/lib/python3.7/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.7/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.7/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/conda/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/opt/conda/lib/python3.7/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/conda/lib/python3.7/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/conda/lib/python3.7/site-packages/anyio/to_thread.py", line 29, in run_sync
    limiter=limiter)
  File "/opt/conda/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "seq2seq/serve_seq2seq.py", line 126, in ask
    outputs = pipe(inputs=Text2SQLInput(utterance=question, db_id=db_id))
  File "/app/seq2seq/utils/pipeline.py", line 76, in __call__
    result = super().__call__(inputs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/text2text_generation.py", line 137, in __call__
    result = super().__call__(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 1101, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 1108, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 1034, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/text2text_generation.py", line 155, in _forward
    output_ids = self.model.generate(**model_inputs, **generate_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/app/seq2seq/utils/picard_model_wrapper.py", line 249, in _generate
    input_ids, decoder_start_token_id=decoder_start_token_id, bos_token_id=bos_token_id
  File "/opt/conda/lib/python3.7/site-packages/transformers/generation_utils.py", line 502, in _prepare_decoder_input_ids_for_generation
    return torch.ones((batch_size, 1), dtype=torch.long, device=self.device) * decoder_start_token_id
TypeError: ones(): argument 'size' must be tuple of ints, but found element of type Tensor at pos 1
01/26/2022 21:50:42 - ERROR - uvicorn.error -   Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/conda/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.7/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/conda/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/opt/conda/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/lib/python3.7/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.7/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.7/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/conda/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/opt/conda/lib/python3.7/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/conda/lib/python3.7/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/conda/lib/python3.7/site-packages/anyio/to_thread.py", line 29, in run_sync
    limiter=limiter)
  File "/opt/conda/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "seq2seq/serve_seq2seq.py", line 126, in ask
    outputs = pipe(inputs=Text2SQLInput(utterance=question, db_id=db_id))
  File "/app/seq2seq/utils/pipeline.py", line 76, in __call__
    result = super().__call__(inputs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/text2text_generation.py", line 137, in __call__
    result = super().__call__(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 1101, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 1108, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 1034, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/text2text_generation.py", line 155, in _forward
    output_ids = self.model.generate(**model_inputs, **generate_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/app/seq2seq/utils/picard_model_wrapper.py", line 249, in _generate
    input_ids, decoder_start_token_id=decoder_start_token_id, bos_token_id=bos_token_id
  File "/opt/conda/lib/python3.7/site-packages/transformers/generation_utils.py", line 502, in _prepare_decoder_input_ids_for_generation
    return torch.ones((batch_size, 1), dtype=torch.long, device=self.device) * decoder_start_token_id
TypeError: ones(): argument 'size' must be tuple of ints, but found element of type Tensor at pos 1
```

**Comment by abhinavgoel95** [comment]
I face a similar problem

**Comment by ishmeetk** [comment]
I even tried on spider dates, and to gives same error.

**Comment by tscholak** [comment]
Hi, let me have a look. This could be a regression due to a recent update of hf transformers...
In the meantime, try to check out commit e37020b6eee18bff865d9d2ba852bd636f3ed777 and see if it works then.

**Comment by tscholak** [comment]
Ok great! Thank you also for confirming that it's the most recent changes that cause this. Now I know where to look 😊

**Comment by ishmeetk** [comment]
Yes no worries. Thank u again for prompt replies and wanted to congratulate you and your team for amazing work.

**Comment by tscholak** [comment]
@ishmeetk @abhinavgoel95 I believe I fixed the problem in the last PR, which has been merged into `main`.

**Comment by abhinavgoel95** [comment]
Perfect. Thank you!

**Comment by ishmeetk** [comment]
Awesome. thank u @tscholak
