### ISSUE TITLE
Issue with loading pipeline onto device

### ISSUE THREAD

**Issue by rbesaleli** [ElementAI/picard#89]
I got the following error when trying to `make serve`:

```
docker pull tscholak/text-to-sql-eval:35f43caadadde292f84e83962fbe5320a65d338f
35f43caadadde292f84e83962fbe5320a65d338f: Pulling from tscholak/text-to-sql-eval
Digest: sha256:46b87fcd776a5707b650bcc08a94f43e152e3b897f8bb4a086838936d2e059b1
Status: Image is up to date for tscholak/text-to-sql-eval:35f43caadadde292f84e83962fbe5320a65d338f
docker.io/tscholak/text-to-sql-eval:35f43caadadde292f84e83962fbe5320a65d338f
mkdir -p -m 777 database
mkdir -p -m 777 transformers_cache
docker run \
	-it \
	--rm \
	--user 13011:13011 \
	-p 8000:8000 \
	--mount type=bind,source=/home/khavv/AutoSQL/picard/database,target=/database \
	--mount type=bind,source=/home/khavv/AutoSQL/picard/transformers_cache,target=/transformers_cache \
	--mount type=bind,source=/home/khavv/AutoSQL/picard/configs,target=/app/configs \
	tscholak/text-to-sql-eval:35f43caadadde292f84e83962fbe5320a65d338f \
	/bin/bash -c "python seq2seq/serve_seq2seq.py configs/serve.json"
Traceback (most recent call last):
  File "seq2seq/serve_seq2seq.py", line 151, in <module>
    main()
  File "seq2seq/serve_seq2seq.py", line 113, in main
    device=backend_args.device,
  File "/app/seq2seq/utils/pipeline.py", line 46, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/text2text_generation.py", line 48, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 758, in __init__
    self.model = self.model.to(self.device)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 852, in to
    return self._apply(convert)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 850, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
make: *** [Makefile:173: serve] Error 1
```

My GPU is working correctly, and I have the correct CUDA version on my local system. I'm able to pull up a text2text-generation pipeline on my GPU outside of Picard. I.e., this works:
```from transformers import pipeline
model = pipeline('text2text-generation', model=<insertmodelhere>, device=0)
```

I don't think this is on my end (I could be wrong). I wonder if something in the dockerfile messes it up. Have you experienced anything like this?

**Comment by tscholak** [comment]
Hi, could be an issue with Docker. Can you try replacing the call to Docker with Nvidia-docker? I've seen this working on Ubuntu.

**Comment by rbesaleli** [comment]
That worked! Thanks so much!
